
SELECT partition_name, high_value 
FROM USER_TAB_PARTITIONS
WHERE TABLE_NAME = 'CSCO_INTERFACE_HOUR'
order by partition_name;


SET SERVEROUTPUT ON
set feedback off
declare
DT DATE;
  
  POS NUMBER := 1;
BEGIN
  EXECUTE IMMEDIATE 'ALTER SESSION SET NLS_DATE_FORMAT = ''DD.MM.YYYY HH24:MI:SS''';
  --DBMS_OUTPUT.PUT_LINE(CHR(45)||CHR(45)||(SYSDATE - 3));
  -- PARTICIONES INTERVAL
  FOR X IN (SELECT TABLE_NAME,PARTITION_NAME, HIGH_VALUE 
            FROM (SELECT * FROM USER_TAB_PARTITIONS WHERE TABLE_NAME != 'TABLERO_UMTS_ULINTFN_WCEL_WEEK')  
            WHERE INTERVAL='YES' 
            AND TABLE_NAME  LIKE '%_HOUR'
            AND TABLESPACE_NAME = 'TBS_HOUR'
            ORDER BY TABLE_NAME,PARTITION_POSITION)
  LOOP
    EXECUTE IMMEDIATE 'SELECT '||X.HIGH_VALUE||' FROM DUAL' INTO DT;
    
    IF TRUNC(DT) <= ADD_MONTHS(SYSDATE-1, -2) THEN--TRUNC(SYSDATE - P_CNT_DIAS) THEN
      --SENTENCIAS.EXTEND();
      --SENTENCIAS(SENTENCIAS.LAST) := SENTENCIA_REC('-- TO DROP PARTITION: '||X.TABLE_NAME||'.'||X.PARTITION_NAME||' HIGH_VALUE '||DT||' --',' ALTER TABLE '||X.TABLE_NAME||' DROP PARTITION '|| X.PARTITION_NAME||' UPDATE INDEXES;');
      DBMS_OUTPUT.PUT_LINE('-- TO DROP PARTITION: '||X.TABLE_NAME||'.'||X.PARTITION_NAME||' HIGH_VALUE '||DT||' --');
      dbms_output.put_line(' ALTER TABLE '||X.TABLE_NAME||' DROP PARTITION '|| X.PARTITION_NAME||' UPDATE INDEXES;');
    END IF;
  END LOOP;

-- PARTICIONES STANDAR
  FOR X IN (SELECT TABLE_NAME,PARTITION_NAME, HIGH_VALUE 
            FROM USER_TAB_PARTITIONS
            WHERE TABLE_NAME IN (SELECT AA.NOMBRE_TABLA
                                FROM (SELECT  NOMBRE_TABLA,
                                              OBSERVACIONES,
                                              NOMBRE_TABLESPACE,
                                              PARTICION_TIPO_TABLA
                                      FROM CALIDAD_PARAMETROS_TABLAS
                                      WHERE NOMBRE_TABLA NOT LIKE 'TEC_%') AA--CALIDAD_PARAMETROS_TABLAS
                                WHERE OBSERVACIONES = 'ENABLED'
                                AND   PARTICION_TIPO_TABLA = 'Hourly'
                                AND NOMBRE_TABLESPACE = 'TBS_HOUR'
                                AND NOMBRE_TABLA LIKE '%_HOUR')
            ORDER BY TABLE_NAME,PARTITION_POSITION)
  LOOP
    EXECUTE IMMEDIATE 'SELECT '||X.HIGH_VALUE||' FROM DUAL' INTO DT;
    
    IF TRUNC(DT) <= ADD_MONTHS(SYSDATE-1, -2) THEN--< TRUNC(SYSDATE - P_CNT_DIAS) THEN
      --SENTENCIAS.EXTEND();
      --SENTENCIAS(SENTENCIAS.LAST) := SENTENCIA_REC('-- TO DROP PARTITION: '||X.TABLE_NAME||'.'||X.PARTITION_NAME||' HIGH_VALUE '||DT||' --',' ALTER TABLE '||X.TABLE_NAME||' DROP PARTITION '|| X.PARTITION_NAME||' UPDATE INDEXES;');
      DBMS_OUTPUT.PUT_LINE('-- TO DROP PARTITION: '||X.TABLE_NAME||'.'||X.PARTITION_NAME||' HIGH_VALUE '||DT||' --');
      dbms_output.put_line(' ALTER TABLE '||X.TABLE_NAME||' DROP PARTITION '|| X.PARTITION_NAME||' UPDATE INDEXES;');
    END IF;
  END LOOP;
END;

--
-- TEST FOR SUBPARTITIONS
--
SET SERVEROUTPUT ON
set feedback ON
declare
DT DATE;
  
  POS NUMBER := 1;
BEGIN
  EXECUTE IMMEDIATE 'ALTER SESSION SET NLS_DATE_FORMAT = ''DD.MM.YYYY HH24:MI:SS''';
  --DBMS_OUTPUT.PUT_LINE(CHR(45)||CHR(45)||(SYSDATE - 3));
  -- PARTICIONES INTERVAL
  FOR X IN (SELECT  PART.TABLE_NAME         TABLE_NAME,
                    PART.PARTITION_NAME     PARTITION_NAME,
                    PART.HIGH_VALUE         HIGH_VALUE,
                    SPART.SUBPARTITION_NAME SUBPARTITION_NAME
            FROM    USER_TAB_PARTITIONS PART
            JOIN    USER_TAB_SUBPARTITIONS SPART
            ON      (PART.TABLE_NAME = SPART.TABLE_NAME
                    AND PART.PARTITION_NAME = SPART.PARTITION_NAME
                    AND PART.TABLESPACE_NAME = 'TBS_HOUR'
                    --AND PART.TABLE_NAME != 'TABLERO_UMTS_ULINTFN_WCEL_WEEK'
                    AND PART.TABLE_NAME LIKE 'UMTS_UL_%'
                    AND PART.INTERVAL = 'YES'
                    AND PART.SUBPARTITION_COUNT > 0)
            ORDER BY PART.TABLE_NAME,PART.PARTITION_POSITION)
  LOOP
    EXECUTE IMMEDIATE 'SELECT '||X.HIGH_VALUE||' FROM DUAL' INTO DT;
    
    --IF TRUNC(DT) <= ADD_MONTHS(SYSDATE-1, -2) THEN--TRUNC(SYSDATE - P_CNT_DIAS) THEN
      --SENTENCIAS.EXTEND();
      --SENTENCIAS(SENTENCIAS.LAST) := SENTENCIA_REC('-- TO DROP PARTITION: '||X.TABLE_NAME||'.'||X.PARTITION_NAME||' HIGH_VALUE '||DT||' --',' ALTER TABLE '||X.TABLE_NAME||' DROP PARTITION '|| X.PARTITION_NAME||' UPDATE INDEXES;');
      DBMS_OUTPUT.PUT_LINE('-- TO DROP PARTITION: '||X.TABLE_NAME||'.'||X.PARTITION_NAME||'SUBPARTITION '||X.SUBPARTITION_NAME||' HIGH_VALUE '||DT||' --');
      DBMS_OUTPUT.PUT_LINE(' ALTER TABLE '||X.TABLE_NAME||' DROP SUBPARTITION '|| X.SUBPARTITION_NAME||' UPDATE INDEXES;');
   -- END IF;
  END LOOP;
end;

